name:  C++ Unit Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  script_check:
    name: Building
    runs-on: ubuntu-18.04
    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: "3.14"

      # - name: Install dependencies
      #   run: |
      #     bash .ci/install_csrc_deps.sh

      - name: Building & Running
        run: |
          mkdir build && cd build
          cmake ..
          make -j && cd ../tests/csrc
          for x in bin/*; do $x; done
